---
- name: Update system
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
  become: true

- name: Apt autopurge
  ansible.builtin.apt:
    autoremove: true
    purge: true
  become: true

- name: Apt autoclean
  ansible.builtin.apt:
    autoclean: true
  become: true

- name: Install vim
  ansible.builtin.apt:
    name: vim
  become: true
